# Generated by Django 4.1.1 on 2022-10-29 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(unique=True),
        ),
    ]
