# Generated by Django 4.1.1 on 2022-10-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_instructor_email_alter_instructor_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='course1',
            new_name='course_1',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='course2',
            new_name='course_2',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='course3',
            new_name='course_3',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='course4',
            new_name='course_4',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='course6',
            new_name='course_6',
        ),
    ]
