# Generated by Django 4.1.1 on 2022-10-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_course_6_schedule_course_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='course_6',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
