# Generated by Django 4.1.1 on 2022-10-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_course_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(default=5276),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.IntegerField(default=3542306, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='child',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_id',
            field=models.IntegerField(default=1603906, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=3625490, unique=True),
        ),
    ]
