# Generated by Django 4.1.1 on 2022-11-30 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_course_course_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_name']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['course_1']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_id', 'first_name', 'last_name']},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='course',
        ),
        migrations.RemoveField(
            model_name='parent',
            name='child',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course_2',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course_3',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course_4',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course_5',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course_6',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(default=9448),
        ),
        migrations.AlterField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.instructor'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.IntegerField(default=4845662, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_id',
            field=models.IntegerField(default=3738461, unique=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='course_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.course'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default=7188414, unique=True),
        ),
    ]
